-- Create Users table for Authentication 
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('teacher', 'student')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Seed an initial teacher user (password is 'admin123' hashed with bcrypt)
-- Using a known hash for demo purposes if the user wants to test immediately
-- INSERT INTO users (email, password_hash, role) VALUES ('teacher@test.com', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6L6.SxD7W.D.N/GK', 'teacher');
