-- Create Students table
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    age INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Skills table
CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Student_Skills junction table
CREATE TABLE student_skills (
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    skill_id BIGINT REFERENCES skills(id) ON DELETE CASCADE,
    proficiency_level INT CHECK (proficiency_level >= 1 AND proficiency_level <= 5),
    assessment_score INT CHECK (assessment_score >= 0 AND assessment_score <= 100),
    PRIMARY KEY (student_id, skill_id)
);
